name: "Run plancosts"
description: "Show cloud cost estimate changes from Terraform in pull requests using plancosts"
author: "Nikhil Amala Jerrin J."
branding:
  icon: "activity"
  color: "blue"

inputs:
  file_prefix:
    description: "Prefix for output file (e.g., base or pr)"
    required: true
  terraform_dir:
    description: "Path to Terraform directory to analyze"
    required: false
    default: ""
  api_url:
    description: "Price API base URL (use host.docker.internal:4000 in CI); no /graphql suffix"
    required: false
    default: ""

outputs:
  monthly_cost:
    description: "Monthly cost estimate from plancosts analysis"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.file_prefix }}
    - ${{ inputs.terraform_dir }}
    - ${{ inputs.api_url }}
