name: Run plancosts
description: Show cloud cost estimate changes from Terraform in pull requests (Infracost-style).
author: you
branding:
  icon: trending-up
  color: blue

inputs:
  terraform_dir:
    description: Path of the Terraform directory (relative to repo root)
    required: true
  percentage_threshold:
    description: Absolute % threshold to trigger a commit comment
    required: false
    default: "0"

outputs:
  master_monthly_cost:
    description: The base branch monthly cost
  pull_request_monthly_cost:
    description: The PR branch monthly cost

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.terraform_dir }}
    - ${{ inputs.percentage_threshold }}
