name: "Run plancosts"
description: "Runs plancosts and writes <prefix>-plancosts.txt"
author: "You"
branding:
  icon: "activity"
  color: "blue"

inputs:
  file_prefix:
    description: "Prefix for output file (e.g., base or pr)"
    required: true
  terraform_dir:
    description: "Absolute path to the Terraform dir (preferred)"
    required: false
    default: ""
  api_url:
    description: "Price API base URL (e.g. http://host.docker.internal:4000)"
    required: false
    default: ""

outputs:
  monthly_cost:
    description: "Extracted monthly cost from OVERALL TOTAL"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.file_prefix }}
    - ${{ inputs.terraform_dir }}
    - ${{ inputs.api_url }}
